# Site settings
title: logX - Self study mathematics for Computer Science and fun
email: hello@logx.in
description: > # Self-study mathematics for computer science and fun. Analysis, Calculus, Statistics, Probability, Linear Algebra, Abstract Algebra all covered.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://logx.in" # the base hostname & protocol for your site
twitter_username: logx_in
github_username:  dailycoder

# Build settings
markdown: kramdown
