# Site settings
title: StartupBusters - Busting fake startups since 1857
email: hello@startupbusters.org
description: > # this means to ignore newlines until "baseurl:"
 With few statups that create value and others that geninune people are working so hard, comes a few chutiyas who try to game the system. For them, startup success is getting funding, wasting the money and then moving on with this being a glorious step for their future. We are startupbusters, we bust these chutiyas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://startupbusters.org" # the base hostname & protocol for your site
twitter_username: startupbusters
github_username:  dailycoder

# Build settings
markdown: kramdown
